/**
 * Cities a candidate can ask to take driving lessons in.
 *
 * Shipped WITH the app rather than synced: the registration screen has to work
 * on a phone with no connection, and this list changes about once a decade.
 * Ordered roughly by size so the common answers need no scrolling; the search
 * box handles the rest.
 */
export const CITIES: readonly string[] = [
  "الدار البيضاء",
  "الرباط",
  "فاس",
  "مراكش",
  "طنجة",
  "سلا",
  "مكناس",
  "أكادير",
  "وجدة",
  "القنيطرة",
  "تطوان",
  "تمارة",
  "آسفي",
  "المحمدية",
  "الجديدة",
  "بني ملال",
  "خريبكة",
  "الناظور",
  "إنزكان",
  "أيت ملول",
  "العرائش",
  "سطات",
  "برشيد",
  "خنيفرة",
  "تازة",
  "الحسيمة",
  "العيون",
  "الداخلة",
  "كلميم",
  "طانطان",
  "الرشيدية",
  "ورزازات",
  "زاكورة",
  "تنغير",
  "ميدلت",
  "إفران",
  "أزرو",
  "صفرو",
  "الصويرة",
  "تارودانت",
  "تيزنيت",
  "سيدي إفني",
  "بيوكرى",
  "أولاد تايمة",
  "اليوسفية",
  "سيدي بنور",
  "أزمور",
  "ابن جرير",
  "قلعة السراغنة",
  "الفقيه بن صالح",
  "وادي زم",
  "بوجعد",
  "الخميسات",
  "تيفلت",
  "سيدي قاسم",
  "سيدي سليمان",
  "مشرع بلقصيري",
  "وزان",
  "شفشاون",
  "المضيق",
  "الفنيدق",
  "مرتيل",
  "القصر الكبير",
  "أصيلة",
  "بنسليمان",
  "بوزنيقة",
  "بركان",
  "تاوريرت",
  "جرادة",
  "بوعرفة",
  "فكيك",
  "جرسيف",
  "تاونات",
  "الحاجب",
  "بولمان",
  "أرفود",
  "الريصاني",
  "أسا",
  "طرفاية",
  "بوجدور",
  "السمارة",
];

/** Case/diacritic-light match good enough for an Arabic city picker. */
export function filterCities(query: string): readonly string[] {
  const q = query.trim();
  if (!q) return CITIES;
  return CITIES.filter((c) => c.includes(q));
}
